// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContencionContencionStatus int32

const (
	Contencion_LISTO   ContencionContencionStatus = 0
	Contencion_NOLISTO ContencionContencionStatus = 1
)

var ContencionContencionStatus_name = map[int32]string{
	0: "LISTO",
	1: "NOLISTO",
}

var ContencionContencionStatus_value = map[string]int32{
	"LISTO":   0,
	"NOLISTO": 1,
}

func (x ContencionContencionStatus) String() string {
	return proto.EnumName(ContencionContencionStatus_name, int32(x))
}

func (ContencionContencionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1, 0}
}

type Message struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Contencion struct {
	Status               ContencionContencionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=grpc.ContencionContencionStatus" json:"status,omitempty"`
	Body                 string                     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Contencion) Reset()         { *m = Contencion{} }
func (m *Contencion) String() string { return proto.CompactTextString(m) }
func (*Contencion) ProtoMessage()    {}
func (*Contencion) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *Contencion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contencion.Unmarshal(m, b)
}
func (m *Contencion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contencion.Marshal(b, m, deterministic)
}
func (m *Contencion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contencion.Merge(m, src)
}
func (m *Contencion) XXX_Size() int {
	return xxx_messageInfo_Contencion.Size(m)
}
func (m *Contencion) XXX_DiscardUnknown() {
	xxx_messageInfo_Contencion.DiscardUnknown(m)
}

var xxx_messageInfo_Contencion proto.InternalMessageInfo

func (m *Contencion) GetStatus() ContencionContencionStatus {
	if m != nil {
		return m.Status
	}
	return Contencion_LISTO
}

func (m *Contencion) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc.ContencionContencionStatus", ContencionContencionStatus_name, ContencionContencionStatus_value)
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterType((*Contencion)(nil), "grpc.Contencion")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x8d, 0xce, 0x8d, 0xbd, 0xe1, 0x28, 0xf1, 0x32, 0x04, 0x61, 0xee, 0x34, 0x14, 0x53,
	0xb7, 0x89, 0xe2, 0xd5, 0x79, 0x19, 0x4c, 0x07, 0xab, 0x27, 0x6f, 0x49, 0x1a, 0x6a, 0x0e, 0xed,
	0x1b, 0x2f, 0x69, 0xc1, 0xbf, 0xc0, 0x7f, 0x5b, 0x4c, 0xcb, 0x74, 0x3d, 0xe5, 0x7d, 0xe1, 0xf7,
	0x7d, 0xf9, 0xf2, 0xe0, 0x7c, 0x47, 0xe8, 0x31, 0xce, 0x8d, 0x73, 0x32, 0x33, 0x22, 0x28, 0xde,
	0xc9, 0x68, 0xa7, 0x27, 0x97, 0xd0, 0x7b, 0xad, 0xaf, 0x39, 0x87, 0x8e, 0xc2, 0xf4, 0x6b, 0xc4,
	0xc6, 0x6c, 0xda, 0xdf, 0x86, 0x79, 0xf2, 0xcd, 0x00, 0x96, 0x58, 0x78, 0x53, 0x68, 0x8b, 0x05,
	0x7f, 0x82, 0xae, 0xf3, 0xd2, 0x97, 0x6e, 0x74, 0x3c, 0x66, 0xd3, 0xe1, 0xfc, 0x4a, 0xfc, 0x86,
	0x88, 0x3f, 0x42, 0xe8, 0xfd, 0x98, 0x04, 0x70, 0xdb, 0x18, 0xf6, 0xe9, 0x27, 0xff, 0xd2, 0xaf,
	0x21, 0x6a, 0xf3, 0xbc, 0x0f, 0xa7, 0xeb, 0x55, 0xf2, 0xbe, 0x89, 0x8e, 0xf8, 0x00, 0x7a, 0x6f,
	0x9b, 0x5a, 0xb0, 0x39, 0xc1, 0xb0, 0x29, 0x9a, 0x18, 0xaa, 0xac, 0x36, 0xfc, 0x06, 0x06, 0xab,
	0xc2, 0x1b, 0xd2, 0x32, 0x57, 0x16, 0xf9, 0x59, 0xdd, 0xa5, 0x81, 0x2e, 0x0e, 0x25, 0x5f, 0x40,
	0xb4, 0x6c, 0x3f, 0xd5, 0x72, 0x44, 0xed, 0xcf, 0x3c, 0x3f, 0x7c, 0xdc, 0x67, 0xd6, 0x7f, 0x96,
	0x4a, 0x68, 0xcc, 0xe3, 0x6a, 0xa6, 0x1f, 0xef, 0xe8, 0x36, 0x35, 0x55, 0xbc, 0x96, 0x0a, 0x49,
	0x7a, 0x24, 0x8b, 0xb3, 0x17, 0xeb, 0x3c, 0x59, 0x55, 0xda, 0x14, 0x5d, 0x1c, 0x56, 0xab, 0xba,
	0xe1, 0x58, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x60, 0xf6, 0x74, 0xf0, 0x78, 0x01, 0x00, 0x00,
}
