// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContencionContencionStatus int32

const (
	Contencion_LISTO   ContencionContencionStatus = 0
	Contencion_NOLISTO ContencionContencionStatus = 1
)

var ContencionContencionStatus_name = map[int32]string{
	0: "LISTO",
	1: "NOLISTO",
}

var ContencionContencionStatus_value = map[string]int32{
	"LISTO":   0,
	"NOLISTO": 1,
}

func (x ContencionContencionStatus) String() string {
	return proto.EnumName(ContencionContencionStatus_name, int32(x))
}

func (ContencionContencionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1, 0}
}

type MessageTermino struct {
	EndSignal            bool     `protobuf:"varint,1,opt,name=endSignal,proto3" json:"endSignal,omitempty"`
	MsgFin               string   `protobuf:"bytes,2,opt,name=msgFin,proto3" json:"msgFin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageTermino) Reset()         { *m = MessageTermino{} }
func (m *MessageTermino) String() string { return proto.CompactTextString(m) }
func (*MessageTermino) ProtoMessage()    {}
func (*MessageTermino) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *MessageTermino) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageTermino.Unmarshal(m, b)
}
func (m *MessageTermino) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageTermino.Marshal(b, m, deterministic)
}
func (m *MessageTermino) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageTermino.Merge(m, src)
}
func (m *MessageTermino) XXX_Size() int {
	return xxx_messageInfo_MessageTermino.Size(m)
}
func (m *MessageTermino) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageTermino.DiscardUnknown(m)
}

var xxx_messageInfo_MessageTermino proto.InternalMessageInfo

func (m *MessageTermino) GetEndSignal() bool {
	if m != nil {
		return m.EndSignal
	}
	return false
}

func (m *MessageTermino) GetMsgFin() string {
	if m != nil {
		return m.MsgFin
	}
	return ""
}

type Contencion struct {
	Status               ContencionContencionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=grpc.ContencionContencionStatus" json:"status,omitempty"`
	NombreEscuadron      string                     `protobuf:"bytes,3,opt,name=nombreEscuadron,proto3" json:"nombreEscuadron,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Contencion) Reset()         { *m = Contencion{} }
func (m *Contencion) String() string { return proto.CompactTextString(m) }
func (*Contencion) ProtoMessage()    {}
func (*Contencion) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *Contencion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contencion.Unmarshal(m, b)
}
func (m *Contencion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contencion.Marshal(b, m, deterministic)
}
func (m *Contencion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contencion.Merge(m, src)
}
func (m *Contencion) XXX_Size() int {
	return xxx_messageInfo_Contencion.Size(m)
}
func (m *Contencion) XXX_DiscardUnknown() {
	xxx_messageInfo_Contencion.DiscardUnknown(m)
}

var xxx_messageInfo_Contencion proto.InternalMessageInfo

func (m *Contencion) GetStatus() ContencionContencionStatus {
	if m != nil {
		return m.Status
	}
	return Contencion_LISTO
}

func (m *Contencion) GetNombreEscuadron() string {
	if m != nil {
		return m.NombreEscuadron
	}
	return ""
}

type Escuadron struct {
	Equipo1              bool     `protobuf:"varint,1,opt,name=equipo1,proto3" json:"equipo1,omitempty"`
	Equipo2              bool     `protobuf:"varint,2,opt,name=equipo2,proto3" json:"equipo2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Escuadron) Reset()         { *m = Escuadron{} }
func (m *Escuadron) String() string { return proto.CompactTextString(m) }
func (*Escuadron) ProtoMessage()    {}
func (*Escuadron) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *Escuadron) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Escuadron.Unmarshal(m, b)
}
func (m *Escuadron) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Escuadron.Marshal(b, m, deterministic)
}
func (m *Escuadron) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Escuadron.Merge(m, src)
}
func (m *Escuadron) XXX_Size() int {
	return xxx_messageInfo_Escuadron.Size(m)
}
func (m *Escuadron) XXX_DiscardUnknown() {
	xxx_messageInfo_Escuadron.DiscardUnknown(m)
}

var xxx_messageInfo_Escuadron proto.InternalMessageInfo

func (m *Escuadron) GetEquipo1() bool {
	if m != nil {
		return m.Equipo1
	}
	return false
}

func (m *Escuadron) GetEquipo2() bool {
	if m != nil {
		return m.Equipo2
	}
	return false
}

type EscuadronUsar struct {
	Equipox              string   `protobuf:"bytes,1,opt,name=equipox,proto3" json:"equipox,omitempty"`
	NombreLab            string   `protobuf:"bytes,2,opt,name=nombreLab,proto3" json:"nombreLab,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EscuadronUsar) Reset()         { *m = EscuadronUsar{} }
func (m *EscuadronUsar) String() string { return proto.CompactTextString(m) }
func (*EscuadronUsar) ProtoMessage()    {}
func (*EscuadronUsar) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *EscuadronUsar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscuadronUsar.Unmarshal(m, b)
}
func (m *EscuadronUsar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscuadronUsar.Marshal(b, m, deterministic)
}
func (m *EscuadronUsar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscuadronUsar.Merge(m, src)
}
func (m *EscuadronUsar) XXX_Size() int {
	return xxx_messageInfo_EscuadronUsar.Size(m)
}
func (m *EscuadronUsar) XXX_DiscardUnknown() {
	xxx_messageInfo_EscuadronUsar.DiscardUnknown(m)
}

var xxx_messageInfo_EscuadronUsar proto.InternalMessageInfo

func (m *EscuadronUsar) GetEquipox() string {
	if m != nil {
		return m.Equipox
	}
	return ""
}

func (m *EscuadronUsar) GetNombreLab() string {
	if m != nil {
		return m.NombreLab
	}
	return ""
}

type EquipoEnviadoPorCentral struct {
	Eepc                 string   `protobuf:"bytes,1,opt,name=eepc,proto3" json:"eepc,omitempty"`
	PrimeraLlegada       bool     `protobuf:"varint,4,opt,name=primeraLlegada,proto3" json:"primeraLlegada,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipoEnviadoPorCentral) Reset()         { *m = EquipoEnviadoPorCentral{} }
func (m *EquipoEnviadoPorCentral) String() string { return proto.CompactTextString(m) }
func (*EquipoEnviadoPorCentral) ProtoMessage()    {}
func (*EquipoEnviadoPorCentral) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{4}
}

func (m *EquipoEnviadoPorCentral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipoEnviadoPorCentral.Unmarshal(m, b)
}
func (m *EquipoEnviadoPorCentral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipoEnviadoPorCentral.Marshal(b, m, deterministic)
}
func (m *EquipoEnviadoPorCentral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipoEnviadoPorCentral.Merge(m, src)
}
func (m *EquipoEnviadoPorCentral) XXX_Size() int {
	return xxx_messageInfo_EquipoEnviadoPorCentral.Size(m)
}
func (m *EquipoEnviadoPorCentral) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipoEnviadoPorCentral.DiscardUnknown(m)
}

var xxx_messageInfo_EquipoEnviadoPorCentral proto.InternalMessageInfo

func (m *EquipoEnviadoPorCentral) GetEepc() string {
	if m != nil {
		return m.Eepc
	}
	return ""
}

func (m *EquipoEnviadoPorCentral) GetPrimeraLlegada() bool {
	if m != nil {
		return m.PrimeraLlegada
	}
	return false
}

func init() {
	proto.RegisterEnum("grpc.ContencionContencionStatus", ContencionContencionStatus_name, ContencionContencionStatus_value)
	proto.RegisterType((*MessageTermino)(nil), "grpc.MessageTermino")
	proto.RegisterType((*Contencion)(nil), "grpc.Contencion")
	proto.RegisterType((*Escuadron)(nil), "grpc.Escuadron")
	proto.RegisterType((*EscuadronUsar)(nil), "grpc.EscuadronUsar")
	proto.RegisterType((*EquipoEnviadoPorCentral)(nil), "grpc.EquipoEnviadoPorCentral")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x09, 0x94, 0x8e, 0x9c, 0x89, 0xae, 0xf2, 0x10, 0x44, 0x15, 0x48, 0x23, 0x17, 0xa8,
	0x42, 0x22, 0xa5, 0x05, 0x81, 0xc6, 0x0d, 0x12, 0x59, 0x8b, 0x90, 0x0a, 0x9b, 0xda, 0xed, 0x86,
	0x3b, 0xc7, 0xb1, 0x32, 0x8b, 0xc6, 0x27, 0x1c, 0x3b, 0x55, 0x5f, 0x86, 0x37, 0xe2, 0xa1, 0x50,
	0x9d, 0x34, 0x11, 0x11, 0x5c, 0xc5, 0xe7, 0xf3, 0xef, 0xdf, 0x27, 0xff, 0x31, 0x9c, 0x16, 0x84,
	0x16, 0x27, 0xb9, 0x34, 0x86, 0x67, 0x32, 0x72, 0x15, 0xeb, 0x65, 0x54, 0x88, 0x70, 0x01, 0x83,
	0xaf, 0x15, 0xbe, 0x96, 0x94, 0x2b, 0x8d, 0xec, 0x29, 0xf8, 0x52, 0xa7, 0x6b, 0x95, 0x69, 0xbe,
	0x09, 0xbc, 0x33, 0x6f, 0xfc, 0x60, 0xd5, 0x02, 0xf6, 0x18, 0xfa, 0xb9, 0xc9, 0x16, 0x4a, 0x07,
	0x77, 0xcf, 0xbc, 0xb1, 0xbf, 0xaa, 0xab, 0xf0, 0x97, 0x07, 0x10, 0xa3, 0xb6, 0x52, 0x0b, 0x85,
	0x9a, 0x9d, 0x43, 0xdf, 0x58, 0x6e, 0x4b, 0xe3, 0x64, 0x83, 0xd9, 0xf3, 0x68, 0x7f, 0x5b, 0xd4,
	0x2a, 0x22, 0xd1, 0x2c, 0xd7, 0x4e, 0xb8, 0xaa, 0x0f, 0xb0, 0x31, 0x9c, 0x68, 0xcc, 0x13, 0x92,
	0x73, 0x23, 0x4a, 0x9e, 0x12, 0xea, 0xe0, 0x9e, 0xbb, 0xaa, 0x8b, 0xc3, 0x97, 0x30, 0xec, 0xba,
	0x30, 0x1f, 0xee, 0x2f, 0xbf, 0xac, 0xaf, 0x2f, 0x87, 0x77, 0xd8, 0x31, 0x1c, 0x7d, 0xbb, 0xac,
	0x0a, 0x2f, 0xfc, 0x08, 0x7e, 0x73, 0x90, 0x05, 0x70, 0x24, 0x7f, 0x96, 0xaa, 0xc0, 0x69, 0xfd,
	0x83, 0x87, 0xb2, 0xdd, 0x99, 0xb9, 0xc6, 0x9b, 0x9d, 0x59, 0xf8, 0x19, 0x1e, 0x36, 0x06, 0x37,
	0x86, 0x53, 0x2b, 0xdd, 0x39, 0x13, 0xff, 0x20, 0xdd, 0xed, 0x13, 0xac, 0x5a, 0x5d, 0xf2, 0xa4,
	0x8e, 0xa9, 0x05, 0xe1, 0x0d, 0x3c, 0x99, 0x3b, 0xe1, 0x5c, 0x6f, 0x15, 0x4f, 0xf1, 0x0a, 0x29,
	0x96, 0xda, 0x12, 0xdf, 0x30, 0x06, 0x3d, 0x29, 0x0b, 0x51, 0xfb, 0xb9, 0x35, 0x7b, 0x01, 0x83,
	0x82, 0x54, 0x2e, 0x89, 0x2f, 0x37, 0x32, 0xe3, 0x29, 0x0f, 0x7a, 0xae, 0xb1, 0x0e, 0x9d, 0xfd,
	0xf6, 0x9a, 0x49, 0xae, 0x25, 0x6d, 0x95, 0x90, 0xec, 0x1c, 0x8e, 0x17, 0x4a, 0x5f, 0x11, 0x66,
	0xc4, 0x73, 0xce, 0x1e, 0x55, 0x33, 0xf8, 0x7b, 0xdc, 0xa3, 0x7f, 0x52, 0x16, 0xc3, 0x30, 0xee,
	0x46, 0xfb, 0xac, 0x52, 0xfe, 0xa7, 0xf9, 0xd1, 0xb0, 0x3b, 0x62, 0xf6, 0x01, 0x58, 0x7c, 0x2b,
	0xc5, 0x8f, 0x0b, 0x65, 0x8a, 0x36, 0xfc, 0x93, 0xda, 0xe6, 0x00, 0x46, 0xa7, 0x1d, 0xb0, 0x4f,
	0xf7, 0xd3, 0xbb, 0xef, 0x6f, 0x33, 0x65, 0x6f, 0xcb, 0x24, 0x12, 0x98, 0x4f, 0xb6, 0x53, 0xf1,
	0xfe, 0x35, 0xbd, 0x4a, 0xe5, 0x76, 0xb2, 0xe4, 0x09, 0x12, 0xb7, 0x48, 0x0a, 0xa7, 0x17, 0xca,
	0x58, 0x52, 0x49, 0xa9, 0x52, 0x34, 0x13, 0xf7, 0xaa, 0x93, 0xbe, 0xfb, 0xbc, 0xf9, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xad, 0xf7, 0xc9, 0x4f, 0xf3, 0x02, 0x00, 0x00,
}
